# Generated by Django 2.2.7 on 2019-11-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCache',
            fields=[
                ('cust_id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('data', models.TextField()),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
