# Generated by Django 2.2.7 on 2019-11-09 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('os_required', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='OSType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.UUIDField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('booked_by', models.UUIDField()),
                ('assigned_by', models.UUIDField()),
                ('quote', models.DecimalField(blank=True, decimal_places=2, max_digits=9, null=True)),
                ('has_charger', models.BooleanField()),
                ('has_case', models.BooleanField()),
                ('other_equipment', models.CharField(blank=True, max_length=255, null=True)),
                ('to_do_by', models.DateField(blank=True, null=True)),
                ('whats_it_doing', models.TextField()),
                ('work_done', models.TextField()),
                ('current_os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_current', to='tickets.OSType')),
                ('equipment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.EquipmentType')),
                ('wanted_os', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_wanted', to='tickets.OSType')),
            ],
        ),
    ]
