# Generated by Django 2.2.7 on 2019-11-10 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='assigned_by',
            new_name='assigned_to',
        ),
    ]
