# Generated by Django 2.2.7 on 2019-11-10 11:33

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20191110_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='whats_it_doing',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='work_done',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
