# Generated by Django 2.2.7 on 2019-11-10 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_auto_20191110_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
