# Generated by Django 2.2.7 on 2019-11-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_ticket_date_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='assigned_to',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
