# Generated by Django 2.2.7 on 2020-01-18 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_ticketrevision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticketrevision',
            options={'ordering': ('-time',)},
        ),
        migrations.AlterField(
            model_name='ticketrevision',
            name='ticket',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='tickets.Ticket'),
        ),
    ]
