# Generated by Django 3.0.4 on 2020-03-07 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticketimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tickets.Status'),
        ),
        migrations.AlterField(
            model_name='ticketrevision',
            name='user',
            field=models.UUIDField(blank=True, null=True),
        ),
    ]
